# Generated by Django 6.0.5 on 2026-05-23 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
            options={
                'verbose_name': 'Покупець',
                'verbose_name_plural': 'Покупці',
                'db_table': 'shop_customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна товару')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'shop_products',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('hire_date', models.DateField(verbose_name='Дата працевлаштування')),
                ('position', models.CharField(choices=[('SELLER', 'Продавець'), ('SENIOR', 'Головний продавець'), ('HEAD', 'Керівник відділу продажів')], default='SELLER', max_length=10, verbose_name='Посада у фірмі')),
            ],
            options={
                'verbose_name': 'Продавець',
                'verbose_name_plural': 'Продавці',
                'db_table': 'shop_sellers',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажу')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість проданого товару')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума продажу')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='ShopApp.customer', verbose_name='Покупець')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_history', to='ShopApp.product', verbose_name='Товар')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ShopApp.seller', verbose_name='Продавець')),
            ],
            options={
                'verbose_name': 'Продаж',
                'verbose_name_plural': 'Продажі',
                'db_table': 'shop_sales',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ShopApp.seller', verbose_name='Закріплений продавець'),
        ),
    ]
