# Generated by Django 6.0.4 on 2026-05-22 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'library_readers',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('regdate', models.DateTimeField()),
                ('genre', models.TextField()),
                ('publishing', models.TextField()),
                ('is_taken', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='BookApp.reader')),
            ],
            options={
                'db_table': 'library_books',
            },
        ),
    ]
